---
title: "MP3"
output: html_document
---


#Part 1
```{r message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(scales)
library(ggplot2)
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")

```

```{r}

western <- "SELECT t.id, t.title, t.production_year, mi1.info AS Genres
FROM title t
JOIN movie_info AS mi1 ON mi1.movie_id = t.id
WHERE production_year IS NOT NULL
AND t.kind_id = 1
AND mi1.info_type_id = 3
AND mi1.info = 'Western'
AND production_year
BETWEEN 1900 AND 2015;
"
data <- db %>%
  dbGetQuery(western)

data_max <-data %>% filter(production_year %in% c("1912","2015"))

ggplot(data, aes(production_year)) +
       geom_histogram(binwidth = 1) +  
  geom_rect(data=data_max, aes(xmin=1912, xmax=1913, ymin= -Inf, ymax= +Inf), 
            inherit.aes = FALSE, fill= "red", alpha = 0.1) +
  geom_rect(data=data_max, aes(xmin=2013, xmax=2014, ymin= -Inf, ymax= +Inf), 
            inherit.aes = FALSE, fill= "red", alpha = 0.1)

```

#Part 2
```{r}
country <- "SELECT t.id, t.title, t.production_year, mi1.info AS Genres, mi2.info AS Country
FROM title t
JOIN movie_info AS mi1 ON mi1.movie_id = t.id
JOIN movie_info AS mi2 ON mi2.movie_id = t.id
WHERE production_year IS NOT NULL
AND t.kind_id = 1
AND mi1.info_type_id = 3
AND mi2.info_type_id = 8
AND mi1.info = 'Western'
AND mi2.info <> 'USA';
"
data_country <- db %>%
  dbGetQuery(country)
data_country_2015 <- data_country %>% filter(production_year == 2015)
data_country_1950 <- data_country %>% filter(production_year == 1950)
dim(data_country_2015)
dim(data_country_1950)

```
